/**
 * 
 */
package com.simiyu.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * @author enocksimiyu
 *
 */
@Entity
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","fieldHandler"})
public class House {

	@Id
	@ApiModelProperty(value = "Unique id generated by the database")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	@ApiModelProperty(value = "Identification number for each house")
	private long house_number;
	@ApiModelProperty(value = "Type of the house, NORMAL, STORY")
	private House_Type house_type;
	@ApiModelProperty(value = "House property occupied or not occupied")
	private boolean occupied;
	@ApiModelProperty(value = "The id for the landload owner of the house")
	private long landload_id;
	
	public House() {
		
	}

	public House(long house_number, House_Type house_type, boolean occupied, long landload_id) {
		this.house_number = house_number;
		this.house_type = house_type;
		this.occupied = occupied;
		this.landload_id = landload_id;
	}

	
	public House(long id, long house_number, House_Type house_type, boolean occupied, long landload_id) {
		this.id = id;
		this.house_number = house_number;
		this.house_type = house_type;
		this.occupied = occupied;
		this.landload_id = landload_id;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getHouse_number() {
		return house_number;
	}

	public void setHouse_number(long house_number) {
		this.house_number = house_number;
	}

	public House_Type getHouse_type() {
		return house_type;
	}

	public void setHouse_type(House_Type house_type) {
		this.house_type = house_type;
	}
	
	public boolean isOccupied() {
		return occupied;
	}

	public void setOccupied(boolean occupied) {
		this.occupied = occupied;
	}	

	public long getLandload_id() {
		return landload_id;
	}

	public void setLandload_id(long landload_id) {
		this.landload_id = landload_id;
	}

	@Override
	public String toString() {
		return "House [id=" + id + ", house_number=" + house_number + ", house_type=" + house_type + ", occupied="
				+ occupied + ", landload_id=" + landload_id + "]";
	}

	
	
}